### ISSUE TITLE
Unreliable pwf2tools tutorial

### ISSUE THREAD

**Issue by BahnDaten** [ptrguide/ptrguide.github.io#1]
There are no pictures in the pwf2tools tutorial, and the tool itself is not very user-friendly.

**Comment by BahnDaten** [comment]
Also, I did not give you permission to put _my_ custom lines onto your website.

**Comment by BahnDaten** [comment]
Also, most of the videos on your website have been deleted, so there is no way of knowing where to start when it comes to video tutorials.

**Comment by pahaze** [comment]
Lol fixed your issues minus the tool being "not user friendly"
